# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Edited by Nir Pikan - knows what he's doing

from PyQt5 import QtCore, QtGui, QtWidgets
from Classes.Calculator import Calculator, ErrorMsg, Course


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, calculator):
        self.calculator = calculator

        # Create main window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create My-GPA-Calculator
        self.myGPAcalcLabel = QtWidgets.QLabel(self.centralwidget)
        self.myGPAcalcLabel.setGeometry(QtCore.QRect(350, 5, 300, 32))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.myGPAcalcLabel.setFont(font)
        self.myGPAcalcLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.myGPAcalcLabel.setObjectName("myGPAcalcLabel")

        # Create messageLabel
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setGeometry(QtCore.QRect(10, 790, 980, 50))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.messageLabel.setStyleSheet("background-color: yellow")
        self.messageLabel.setFont(font)
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")

        # Create myCoursesLabel
        self.myCoursesLabel = QtWidgets.QLabel(self.centralwidget)
        self.myCoursesLabel.setGeometry(QtCore.QRect(20, 40, 122, 24))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.myCoursesLabel.setFont(font)
        self.myCoursesLabel.setObjectName("myCoursesLabel")

        # Create totalPointsLabel
        self.totalPointsLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalPointsLabel.setGeometry(QtCore.QRect(770, 100, 250, 24))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.totalPointsLabel.setFont(font)
        self.totalPointsLabel.setObjectName("totalPointsLabel")

        # Create gpaLabel
        self.gpaLabel = QtWidgets.QLabel(self.centralwidget)
        self.gpaLabel.setGeometry(QtCore.QRect(770, 140, 200, 24))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.gpaLabel.setFont(font)
        self.gpaLabel.setObjectName("gpaLabel")

        # Create nameLabel
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(120, 80, 81, 20))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")

        # Create pointsLabel
        self.pointsLabel = QtWidgets.QLabel(self.centralwidget)
        self.pointsLabel.setGeometry(QtCore.QRect(330, 80, 81, 20))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pointsLabel.setFont(font)
        self.pointsLabel.setObjectName("pointsLabel")

        # Create gradeLabel
        self.gradeLabel = QtWidgets.QLabel(self.centralwidget)
        self.gradeLabel.setGeometry(QtCore.QRect(540, 80, 81, 20))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gradeLabel.setFont(font)
        self.gradeLabel.setObjectName("gradeLabel")

        # Create frame-grid-scroll area for courses
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 90, 761, 281))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")

        self.coursesScrollArea = QtWidgets.QScrollArea(self.frame)
        self.coursesScrollArea.setWidgetResizable(True)
        self.coursesScrollArea.setObjectName("coursesScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(5, 5, 5, -1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.coursesScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.coursesScrollArea, 0, 1, 1, 1)

        # Create Add-course base
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 370, 741, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Add-course name
        self.nameAddLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.nameAddLineEdit.setObjectName("nameAddLineEdit")
        self.horizontalLayout.addWidget(self.nameAddLineEdit)

        # Add-course pointsSpinBox
        self.pointsSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.pointsSpinBox.setWrapping(False)
        self.pointsSpinBox.setFrame(True)
        self.pointsSpinBox.setReadOnly(False)
        self.pointsSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.pointsSpinBox.setPrefix("")
        self.pointsSpinBox.setSuffix("")
        self.pointsSpinBox.setMinimum(1.0)
        self.pointsSpinBox.setMaximum(10.0)
        self.pointsSpinBox.setSingleStep(0.5)
        self.pointsSpinBox.setObjectName("pointsSpinBox")
        self.horizontalLayout.addWidget(self.pointsSpinBox)
        self.pointsSpinBox.valueChanged.connect(self.set_course_points)

        # Add-course gradeSpinBox
        self.gradeSpinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.gradeSpinBox.setMaximum(100)
        self.gradeSpinBox.setObjectName("gradeSpinBox")
        self.horizontalLayout.addWidget(self.gradeSpinBox)

        # Add-course button
        self.addCourseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addCourseButton.setObjectName("addCourseButton")
        self.horizontalLayout.addWidget(self.addCourseButton)
        self.addCourseButton.clicked.connect(self.add_course_clicked)

        # Create features label
        self.featuresLabel = QtWidgets.QLabel(self.centralwidget)
        self.featuresLabel.setGeometry(QtCore.QRect(20, 450, 122, 24))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.featuresLabel.setFont(font)
        self.featuresLabel.setObjectName("featuresLabel")

        # Create Top3 results
        self.top3VerticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.top3VerticalLayoutWidget.setGeometry(QtCore.QRect(270, 480, 351, 81))
        self.top3VerticalLayoutWidget.setObjectName("top3VerticalLayoutWidget")
        self.top3VerticalLayout = QtWidgets.QVBoxLayout(self.top3VerticalLayoutWidget)
        self.top3VerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.top3VerticalLayout.setObjectName("top3VerticalLayout")

        # First result
        self.top3Label = QtWidgets.QLabel(self.top3VerticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(14)
        self.top3Label.setFont(font)
        self.top3Label.setObjectName("top3Label")
        self.top3VerticalLayout.addWidget(self.top3Label)

        # Second result
        self.top3Label_2 = QtWidgets.QLabel(self.top3VerticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(14)
        self.top3Label_2.setFont(font)
        self.top3Label_2.setObjectName("top3Label_2")
        self.top3VerticalLayout.addWidget(self.top3Label_2)

        # 3rd result
        self.top3Label_3 = QtWidgets.QLabel(self.top3VerticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(14)
        self.top3Label_3.setFont(font)
        self.top3Label_3.setObjectName("top3Label_3")
        self.top3VerticalLayout.addWidget(self.top3Label_3)

        # Create top3Button
        self.top3Button = QtWidgets.QPushButton(self.centralwidget)
        self.top3Button.setGeometry(QtCore.QRect(20, 480, 241, 81))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(14)
        self.top3Button.setFont(font)
        self.top3Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.top3Button.setObjectName("top3Button")

        # Create menubar
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        # Create statusbar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.myGPAcalcLabel.setText(_translate("MainWindow", "My-GPA-Calculator"))
        self.myCoursesLabel.setText(_translate("MainWindow", "My Courses"))
        self.totalPointsLabel.setText(_translate("MainWindow", "Total Points: 0"))
        self.gpaLabel.setText(_translate("MainWindow", "GPA: 0"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.pointsLabel.setText(_translate("MainWindow", "Points"))
        self.gradeLabel.setText(_translate("MainWindow", "Grade"))
        # self.deleteButton_2.setText(_translate("MainWindow", "Delete"))
        # self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.addCourseButton.setText(_translate("MainWindow", "Add"))
        self.featuresLabel.setText(_translate("MainWindow", "Features"))
        self.top3Label.setText(_translate("MainWindow", "1."))
        self.top3Label_2.setText(_translate("MainWindow", "2."))
        self.top3Label_3.setText(_translate("MainWindow", "3."))
        self.top3Button.setText(_translate("MainWindow", "Top 3 courses to improve"))

    # When the addCourseButton is clicked
    def add_course_clicked(self, calculator):
        created_course = self.calculator.add_course(
            self.nameAddLineEdit.text(), self.pointsSpinBox.value(), self.gradeSpinBox.value())

        # In case of an error
        if type(created_course) is ErrorMsg:
            self.messageLabel.setText(created_course.msg)
            print(created_course.msg)
            return

        # Update text
        print(created_course.name, created_course.points, created_course.grade)
        self.messageLabel.setText("Course ''%s'' was added!" % created_course.name)
        self.totalPointsLabel.setText("Total Points: %.1f" % self.calculator.points)
        self.gpaLabel.setText("GPA: %.2f" % self.calculator.gpa)

        # Add course to UI
        # Add check_box
        check_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        check_box.setText("")
        check_box.setChecked(True)
        check_box.setTristate(False)
        check_box.stateChanged.connect(
            lambda: self.set_checkbox_to_course(created_course, check_box.checkState()))
        self.gridLayout_2.addWidget(check_box, self.calculator.courses_count, 0, 1, 1)

        # Add nameLineEdit
        name_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        name_line_edit.setText(created_course.name)
        name_line_edit.setReadOnly(True)
        name_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_2.addWidget(name_line_edit, self.calculator.courses_count, 1, 1, 1)

        # Add pointsLineEdit
        points_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        points_line_edit.setText(str(created_course.points))
        points_line_edit.setReadOnly(True)
        points_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_2.addWidget(points_line_edit, self.calculator.courses_count, 2, 1, 1)

        # Add gradeLineEdit
        grade_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        grade_line_edit.setText(str(created_course.grade))
        grade_line_edit.setReadOnly(True)
        grade_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_2.addWidget(grade_line_edit, self.calculator.courses_count, 3, 1, 1)

        # Add deleteButton
        delete_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        delete_button.setText("Delete")
        delete_button.clicked.connect(lambda: self.remove_row(delete_button,created_course))
        self.gridLayout_2.addWidget(delete_button, self.calculator.courses_count, 4, 1, 1)

    # Makes sure that the pointsSpinBox will have logical values
    def set_course_points(self, value):
        x = float(value)
        if not (x * 2).is_integer():
            self.pointsSpinBox.setValue(int(x))

    # Connects a course to his checkbox
    def set_checkbox_to_course(self, course, value):
        course.enabled = value
        if course.enabled:
            text = "enabled!"
        else:
            text = "disabled!"
        self.messageLabel.setText("Course ''" + course.name + "'' is " + text)

    # When the deleteCourseButton is clicked
    def remove_row(self, sender, course):
        self.calculator.remove_course(course)

        index = self.gridLayout_2.indexOf(sender)
        row = self.gridLayout_2.getItemPosition(index)[0]
        for column in range(self.gridLayout_2.columnCount()):
            layout = self.gridLayout_2.itemAtPosition(row, column)
            if layout is not None:
                layout.widget().deleteLater()
                self.gridLayout_2.removeItem(layout)

        # Update text
        print(course.name, course.points, course.grade)
        self.messageLabel.setText("Course ''%s'' was deleted!" % course.name)
        self.totalPointsLabel.setText("Total Points: %.1f" % self.calculator.points)
        self.gpaLabel.setText("GPA: %.2f" % self.calculator.gpa)
